"use client";

import { useState } from "react";
import { ExternalLink, Plus, Trash2 } from "lucide-react";
import { useOperator } from "@/components/operator-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { ActivityKind, EvidenceKind } from "@/lib/types";

export function ActivityLog({ slug }: { slug: string }) {
  const operator = useOperator(); const [text, setText] = useState(""); const [kind, setKind] = useState<ActivityKind>("note");
  const entries = operator.activity.filter((entry) => entry.projectSlug === slug);
  return <section className="mission-panel"><header className="mission-panel-header"><div><p className="eyebrow">Field log</p><h2 className="font-heading text-xl">What actually happened</h2></div></header><div className="space-y-3 p-4"><div className="flex gap-2"><select value={kind} onChange={(e) => setKind(e.target.value as ActivityKind)} className="h-9 rounded-md border bg-background px-2 text-sm">{["note","decision","test","discovery","failure","milestone","hardware"].map((item) => <option key={item}>{item}</option>)}</select><Input value={text} onChange={(e) => setText(e.target.value)} placeholder="Add a durable log entry…" onKeyDown={(e) => { if (e.key === "Enter" && text.trim()) { operator.addActivity({ projectSlug: slug, kind, text: text.trim() }); setText(""); } }} /><Button size="icon" aria-label="Add log entry" onClick={() => { if (text.trim()) { operator.addActivity({ projectSlug: slug, kind, text: text.trim() }); setText(""); } }}><Plus /></Button></div>{entries.length ? <ol className="space-y-3">{entries.map((entry) => <li key={entry.id} className="border-l border-primary/30 pl-3"><p className="text-sm leading-6">{entry.text}</p><p className="mt-1 font-mono text-[11px] uppercase tracking-wider text-muted-foreground">{entry.kind} · {new Date(entry.at).toLocaleString()}</p></li>)}</ol> : <p className="text-sm text-muted-foreground">No field entries yet. Memory is currently operating without a net.</p>}</div></section>;
}

export function EvidenceLocker({ slug }: { slug: string }) {
  const operator = useOperator(); const [label, setLabel] = useState(""); const [href, setHref] = useState(""); const [note, setNote] = useState(""); const [kind, setKind] = useState<EvidenceKind>("document");
  const entries = operator.evidence.filter((entry) => entry.projectSlug === slug);
  function add() { if (!label.trim()) return; operator.addEvidence({ projectSlug: slug, kind, label: label.trim(), href: href.trim() || undefined, note: note.trim() || undefined }); setLabel(""); setHref(""); setNote(""); }
  return <section className="mission-panel"><header className="mission-panel-header"><div><p className="eyebrow">Evidence locker</p><h2 className="font-heading text-xl">Proof and source material</h2></div></header><div className="space-y-3 p-4"><div className="grid gap-2 sm:grid-cols-[9rem_1fr]"><select value={kind} onChange={(e) => setKind(e.target.value as EvidenceKind)} className="h-9 rounded-md border bg-background px-2 text-sm">{["repository","readme","image","demo","test","diagram","document","command"].map((item) => <option key={item}>{item}</option>)}</select><Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Evidence label" /><Input value={href} onChange={(e) => setHref(e.target.value)} placeholder="URL or file path" className="sm:col-start-2" /><Textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Optional note" className="min-h-20 sm:col-start-2" /></div><Button size="sm" onClick={add}><Plus />Add evidence</Button>{entries.length ? <ul className="divide-y divide-border">{entries.map((entry) => <li key={entry.id} className="flex items-start justify-between gap-3 py-3"><div><p className="font-medium">{entry.label}</p><p className="font-mono text-[11px] uppercase tracking-wider text-primary">{entry.kind}</p>{entry.note ? <p className="mt-1 text-sm text-muted-foreground">{entry.note}</p> : null}{entry.href ? <a href={entry.href} target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-1 break-all text-sm text-primary hover:underline"><ExternalLink className="size-3" />{entry.href}</a> : null}</div><Button size="icon-sm" variant="ghost" aria-label="Remove evidence" onClick={() => operator.removeEvidence(entry.id)}><Trash2 className="size-4" /></Button></li>)}</ul> : <p className="text-sm text-muted-foreground">Locker empty. The publish gate is going to ask questions.</p>}</div></section>;
}
