'use strict';
const notes={
alfred:{label:'Alfred',category:'P—01 / LOCAL INTELLIGENCE',title:'An AI with a home.',lead:'Alfred starts with a simple ambition: make useful intelligence part of everyday life, with continuity and a place of its own.',blocks:[['The idea','A local AI system for Josh and his family. A place for questions, project knowledge, and the things worth remembering between conversations.'],['Inside the experiment','The work spans local models, personal knowledge, and a capture pipeline for turning recordings into useful information. These are pieces being developed toward a larger system, not a claim that every part is finished.'],['The next layer','The Alfred–Oracle concept pairs local continuity with on-demand specialist help when a problem needs more horsepower. Alfred keeps the thread; specialists help untangle it.']],aside:'A very elaborate answer to “where did I put that thought?”',links:[['presence','What makes intelligence feel present?'],['oracle','Meet the Alfred–Oracle idea'],['batdeck','What if Alfred could come along?']]},
dragons:{label:'Dragons',category:'P—02 / ROBOTICS + IMAGINATION',title:'First, make it move.<br>Then, make it matter.',lead:'An animatronic dragon project with Josh’s daughters—where mechanical design meets the rather unreasonable wish to bring a creature to life.',blocks:[['The idea','Build quadruped companions that can move and express a little personality. Start with the mechanics, then explore the shape and behavior that make them feel like creatures.'],['The interesting problem','A joint can move correctly and still feel mechanical. Weight shifts, timing, pauses, and where a creature appears to look all change how we interpret the same hardware.'],['On the workbench','The project explores a quadruped chassis, custom body shells, actuator choices, and spring-assisted counterbalancing. The design has to reconcile the imagined creature with the space, mass, and forces of the real one.']],aside:'The engineering requirement “my daughters think it’s alive” is surprisingly difficult to quantify.',links:[['presence','How does motion become personality?'],['counterbalance','Why give a robot springs?'],['secondlife','Follow the parts back to the beginning']]},
cospace:{label:'Co-Space',category:'P—03 / SHARED VIRTUAL WORLDS',title:'Same room.<br>Another world.',lead:'Co-Space explores a shared VR experience where two people can inhabit the same virtual place while standing in the same physical room.',blocks:[['The idea','A shared experience begins with a shared frame of reference. Two headsets need to agree on where the world is—and where the other person is within it.'],['Inside the experiment','The prototype work combines Unity, headset tracking, multiplayer networking, and calibration. The core question is how to make two perspectives line up well enough for a shared sense of place.'],['Beyond the technical problem','The motivation is an experience you can take someone into. A virtual workshop tour is one possible destination: arrive outside the doors, then step inside together.']],aside:'“Let me show you around” gets considerably more interesting when the room can change.',links:[['invitation','Where might those doors lead?'],['presence','Why does being there together feel different?'],['dragons','What else might live in that world?']]},
batdeck:{label:'BATDECK',category:'P—04 / HARDWARE REIMAGINED',title:'A second life.<br>A new mission.',lead:'The BATDECK is a concept for a portable Alfred field terminal—an excuse to turn recovered hardware into something worth carrying.',blocks:[['The idea','Reimagine an old display device as a compact, characterful terminal. A cyberdeck with a useful purpose: a physical point of contact with Alfred.'],['What exists so far','This is an early redesign concept, with donor-hardware inspection and enclosure possibilities to explore. The final hardware architecture, controls, and form factor remain open.'],['The design question','How much of the original hardware can serve the new purpose? That answer should guide the enclosure and interface, instead of forcing the components into a shape they cannot support.']],aside:'A perfectly normal response to finding an old screen. Depending on your definition of normal.',links:[['secondlife','Why start with something discarded?'],['alfred','Meet the intelligence on the other end'],['underneath','Look a little closer']]},
presence:{label:'Presence',category:'THREAD 01 / THE FEELING OF BEING THERE',title:'When does a machine<br>feel present?',lead:'A connection worth exploring: presence might depend as much on timing and context as on raw capability.',blocks:[['A dragon pauses','A tiny pause before a head turn could make movement feel like attention. The motor has not become smarter; the behavior has become easier for a person to read.'],['Alfred remembers','A system that carries a useful thread forward can feel more continuous than one that starts from zero each time. That is a design goal for Alfred, not a claim of consciousness.'],['A friend stands beside you','In Co-Space, a shared location and a responding point of view may do more for the experience than a more detailed virtual wall. Each project asks what makes an interaction feel coherent.']],aside:'Three different workbenches. One surprisingly human question.',links:[['dragons','Follow the movement'],['alfred','Follow the continuity'],['cospace','Follow the shared point of view']]},
secondlife:{label:'Second lives',category:'THREAD 02 / THE POSSIBILITIES IN THE PARTS',title:'The parts already<br>have a past.',lead:'A salvaged component arrives with constraints, clues, and a story. Those can become the starting point for the next invention.',blocks:[['Start by understanding','What did it do? How does it move, connect, or sense? An inventory becomes more useful when it captures capabilities, not just names.'],['Let the constraints suggest something','The dimensions of a screen can shape a field terminal. An actuator can suggest a new mechanism. Reuse is also a way of discovering ideas that would not emerge from a blank shopping list.'],['The Scrap Alchemist connection','Scrap Alchemist is an app concept built around that process: understand the parts, compare their possibilities, and connect an inventory to project ideas.']],aside:'“I might need that” becomes more convincing when you can explain what it does.',links:[['batdeck','Follow a screen into the BATDECK'],['counterbalance','Follow a mechanical constraint'],['underneath','Inspect the philosophy underneath']]},
invitation:{label:'The invitation',category:'THREAD 03 / A WORKSHOP YOU CAN ENTER',title:'What if this door<br>opened in VR?',lead:'This website is one front door. A shared virtual tour could become another.',blocks:[['The imagined arrival','Two people calibrate their headsets and arrive outside WeaselNet Labs. The tour starts with a familiar line: “Welcome. Let me show you around.”'],['The possibility','Instead of just reading about a project, imagine standing beside it: a creature on the workbench, a terminal waiting for input, a doorway into a different experiment.'],['The honest boundary','That tour is a future concept. Co-Space is the work toward the shared foundation; this site is a first way to tell the stories and explore the connections.']],aside:'The visitor waiver is, for now, purely imaginary.',links:[['cospace','Explore the shared-world foundation'],['dragons','Visit the creature workbench'],['presence','Follow the idea of presence']]},
oracle:{label:'Oracle',category:'SIDE NOTE / THE ALFRED–ORACLE CONCEPT',title:'Keep the thread.<br>Call in the specialists.',lead:'An architecture idea for giving Alfred access to extra problem-solving capability without giving up the continuity of a local system.',blocks:[['Alfred’s role','Maintain the personal context and the long-running thread of work. Know what the question belongs to.'],['The specialist’s role','Take on a bounded problem when additional capability would help, then return a useful result for Alfred to integrate.'],['A question still worth asking','What is the smallest useful context a specialist needs? The handoff should be deliberate, understandable, and appropriate to the task.']],aside:'Even a very capable butler is allowed to call a specialist.',links:[['alfred','Back to Alfred'],['batdeck','Give the system a physical doorway'],['presence','Why continuity matters']]},
counterbalance:{label:'Springs & gravity',category:'SIDE NOTE / A ROBOT’S NEGOTIATION WITH GRAVITY',title:'Let the mechanism<br>share the work.',lead:'One avenue in the dragon design is spring-assisted counterbalancing: use the mechanism to help support its own weight.',blocks:[['The question','If an actuator spends much of its effort holding a limb against gravity, could a spring help carry some of that load?'],['The tradeoff','The spring’s assistance changes with geometry. A useful design needs to account for the full motion range, not just one comfortable pose. It also needs to avoid turning stored energy into unwanted motion.'],['Why it belongs here','It is the kind of problem that rewards understanding the parts together. The interesting answer may involve different actuator sizes, mechanical leverage, and passive support.']],aside:'Gravity is a remarkably persistent design reviewer.',links:[['dragons','Return to the dragon'],['secondlife','Follow the possibilities in the hardware']]},
underneath:{label:'Underneath',category:'YOU FOUND THE SMALL DOOR',title:'Of course you<br>looked underneath.',lead:'That instinct is more or less the reason this workshop exists.',blocks:[['An unofficial workshop rule','Before deciding what something could become, try to understand what it is. Follow the cable. Inspect the mechanism. Ask the extra question.'],['A second unofficial rule','An unfinished idea is allowed to be interesting. Give it enough structure to explore, and be honest about the pieces that still need work.']],aside:'You have passed the entirely unaccredited WeaselNet curiosity assessment.',links:[['secondlife','There’s a whole shelf of possibilities'],['invitation','Or perhaps another door'],['oracle','Or a question that needs a specialist']]}
};
const dialog=document.querySelector('#field-notes');
let history=[];
let previousFocus=null;
const trail=document.querySelector('#trail');
function renderNote(key){
 const note=notes[key];
 document.querySelector('#note-category').textContent=note.category;
 document.querySelector('#note-title').innerHTML=note.title;
 document.querySelector('#note-lead').textContent=note.lead;
 const content=document.querySelector('#note-content');content.replaceChildren();
 for(const [title,body] of note.blocks){const block=document.createElement('div');block.className='note-block';const heading=document.createElement('h3');heading.textContent=title;const paragraph=document.createElement('p');paragraph.textContent=body;block.append(heading,paragraph);content.append(block);}
 const aside=document.createElement('p');aside.className='note-aside';aside.textContent=note.aside;content.append(aside);
 const links=document.querySelector('#note-links');links.replaceChildren();
 for(const [target,label] of note.links){const button=document.createElement('button');button.className='note-link';const text=document.createElement('span');text.textContent=label;const arrow=document.createElement('span');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');button.append(text,arrow);button.addEventListener('click',()=>openNote(target));links.append(button);}
 trail.replaceChildren();
 history.forEach((entry,index)=>{if(index){const sep=document.createElement('span');sep.textContent='/';sep.setAttribute('aria-hidden','true');trail.append(sep);}if(index===history.length-1){const current=document.createElement('span');current.textContent=notes[entry].label;current.setAttribute('aria-current','page');trail.append(current);}else{const back=document.createElement('button');back.textContent=notes[entry].label;back.addEventListener('click',()=>{history=history.slice(0,index+1);renderNote(entry);focusTitle();});trail.append(back);}});
 document.querySelector('#depth').textContent=history.length>1?`${history.length-1} ${history.length===2?'turn':'turns'} down the rabbit hole. Follow a breadcrumb above to head back.`:'A starting point. Choose a connection and see where it goes.';
 document.querySelector('.dialog-scroll').scrollTop=0;
}
function focusTitle(){const heading=document.querySelector('#note-title');heading.tabIndex=-1;heading.focus({preventScroll:true});}
function openNote(key){if(!notes[key])return;const starting=!dialog.open;if(starting){history=[];previousFocus=document.activeElement;}history.push(key);renderNote(key);if(starting){dialog.showModal();document.body.classList.add('notes-open');}focusTitle();}
document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>openNote(button.dataset.open)));
document.querySelector('#close-notes').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{const r=dialog.getBoundingClientRect();if(event.target===dialog&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom))dialog.close();});
dialog.addEventListener('close',()=>{document.body.classList.remove('notes-open');if(previousFocus&&previousFocus.isConnected)previousFocus.focus({preventScroll:true});});
let lastThread=-1;document.querySelector('#surprise').addEventListener('click',()=>{const threads=['presence','secondlife','invitation','oracle','counterbalance'];let pick;do{pick=Math.floor(Math.random()*threads.length);}while(pick===lastThread);lastThread=pick;openNote(threads[pick]);});
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.07});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.documentElement.classList.add('motion-ready');}
